---
- name: Install XRDP
  apt:
    name: xrdp
    state: present
    update_cache: true

- name: Ensure xrdp installed and started
  systemd:
    name: xrdp
    enabled: true
    state: started
    daemon_reload: true

- name: Create xrdp groups
  group:
    name: "{{ item.usergroup }}"
    state: present
  loop: "{{ xrdp_users }}"

- name: Create xrdp users
  user:
    name: "{{ item.username }}"
    group: "{{ item.usergroup }}"
    password: "{{ item.userpass | password_hash('sha512', 'mySecretSalt') }}"
    shell: /bin/bash
    skeleton: /etc/skel
  loop: "{{ xrdp_users }}"

- name: Create xsession file
  copy:
    dest: "/home/{{ item.username }}/.xsession"
    content: "xfce4-session"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup }}"
    mode: '0755'
  loop: "{{ xrdp_users }}"
  notify: Restart xrdp
